`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Module Name: tb_branch_full
// Description: CPU integration coverage for instructions that were decoded but
//              never exercised end-to-end by tb_branch.v: AUIPC, JALR, and the
//              four remaining branch types (BNE, BGE, BLTU, BGEU). Encodings were
//              generated with a small Python RV32I encoder to avoid hand-encoding
//              errors (see comments per instruction for the intended semantics).
//
//              BLTU/BGEU specifically use operands where the signed and unsigned
//              interpretations disagree (-1 vs. 1) so that a decoder bug that
//              silently reused the signed BLT/BGE comparison would be caught.
//////////////////////////////////////////////////////////////////////////////////

module tb_branch_full;

    reg clk;
    reg rst_n;
    wire [31:0] mem_addr;
    wire [31:0] mem_write_data;
    wire        mem_write_en;
    wire        mem_read_en;
    reg  [31:0] mem_read_data;
    wire [31:0] debug_pc;

    cpu_top uut (
        .clk            (clk),
        .rst_n          (rst_n),
        .mem_addr       (mem_addr),
        .mem_write_data (mem_write_data),
        .mem_write_en   (mem_write_en),
        .mem_read_en    (mem_read_en),
        .mem_read_data  (mem_read_data),
        .debug_pc       (debug_pc)
    );

    always #10 clk = ~clk;

    integer pass_count = 0;
    integer fail_count = 0;

    task check_reg;
        input [4:0]   reg_num;
        input [31:0]  expected;
        input [255:0] name;
        begin
            if (uut.regfile.regs[reg_num] === expected) begin
                $display("  PASS  %s: x%0d = 0x%h", name, reg_num, expected);
                pass_count = pass_count + 1;
            end else begin
                $display("  FAIL  %s: x%0d = 0x%h (expected 0x%h)",
                         name, reg_num, uut.regfile.regs[reg_num], expected);
                fail_count = fail_count + 1;
            end
        end
    endtask

    task wait_cycles;
        input integer n;
        integer j;
        begin
            for (j = 0; j < n; j = j + 1) @(posedge clk);
            #1;
        end
    endtask

    initial begin
        $dumpfile("sim/tb_branch_full.vcd");
        $dumpvars(0, tb_branch_full);

        clk = 0;
        rst_n = 0;
        mem_read_data = 32'd0;

        $display("=== AUIPC / JALR / BNE / BGE / BLTU / BGEU Testbench ===\n");

        // Generated by tools' Python RV32I encoder (see instruction encodings below).
        uut.imem.mem[ 0] = 32'h00005097; // AUIPC x1, 0x5      -> x1 = PC(0)+0x5000 = 0x00005000
        uut.imem.mem[ 1] = 32'h02000113; // ADDI  x2, x0, 32   -> x2 = 32
        uut.imem.mem[ 2] = 32'h004101E7; // JALR  x3, 4(x2)    -> x3=PC+4=12, jump to (32+4)&~1=36
        uut.imem.mem[ 3] = 32'h3E700493; // ADDI  x9, x0, 999  -> SKIPPED (poison: proves jump taken)
        uut.imem.mem[ 4] = 32'h00000013; // NOP (padding, SKIPPED)
        uut.imem.mem[ 5] = 32'h00000013;
        uut.imem.mem[ 6] = 32'h00000013;
        uut.imem.mem[ 7] = 32'h00000013;
        uut.imem.mem[ 8] = 32'h00000013;
        uut.imem.mem[ 9] = 32'h03700293; // ADDI  x5, x0, 55   -> x5=55  <JALR target, PC=36>
        uut.imem.mem[10] = 32'h00000013; // NOP

        uut.imem.mem[11] = 32'hFFB00693; // ADDI x13, x0, -5   -> x13 = 0xFFFFFFFB (-5)
        uut.imem.mem[12] = 32'h00300713; // ADDI x14, x0, 3    -> x14 = 3
        uut.imem.mem[13] = 32'h00E6D463; // BGE  x13, x14, +8  -> signed -5>=3? false -> NOT taken
        uut.imem.mem[14] = 32'h00100793; // ADDI x15, x0, 1    -> x15=1 (fallthrough proof)
        uut.imem.mem[15] = 32'h00D75463; // BGE  x14, x13, +8  -> signed 3>=-5? true -> taken
        uut.imem.mem[16] = 32'h3E700813; // ADDI x16, x0, 999  -> SKIPPED
        uut.imem.mem[17] = 32'h00000013; // NOP SKIPPED
        uut.imem.mem[18] = 32'h02A00813; // ADDI x16, x0, 42   -> x16=42  <BGE taken target>
        uut.imem.mem[19] = 32'h00000013; // NOP

        uut.imem.mem[20] = 32'h00500893; // ADDI x17, x0, 5
        uut.imem.mem[21] = 32'h00500913; // ADDI x18, x0, 5
        uut.imem.mem[22] = 32'h01289463; // BNE  x17, x18, +8  -> 5!=5 false -> NOT taken
        uut.imem.mem[23] = 32'h00700993; // ADDI x19, x0, 7    -> x19=7 (fallthrough proof)
        uut.imem.mem[24] = 32'h00900913; // ADDI x18, x0, 9    -> x18=9
        uut.imem.mem[25] = 32'h01289463; // BNE  x17, x18, +8  -> 5!=9 true -> taken
        uut.imem.mem[26] = 32'h3E700A13; // ADDI x20, x0, 999  -> SKIPPED
        uut.imem.mem[27] = 32'h00000013; // NOP SKIPPED
        uut.imem.mem[28] = 32'h05800A13; // ADDI x20, x0, 88   -> x20=88  <BNE taken target>
        uut.imem.mem[29] = 32'h00000013; // NOP

        uut.imem.mem[30] = 32'hFFF00A93; // ADDI x21, x0, -1   -> x21 = 0xFFFFFFFF
        uut.imem.mem[31] = 32'h00100B13; // ADDI x22, x0, 1    -> x22 = 1
        uut.imem.mem[32] = 32'h016AE463; // BLTU x21, x22, +8  -> unsigned 0xFFFFFFFF<1? false -> NOT taken
        uut.imem.mem[33] = 32'h00300B93; // ADDI x23, x0, 3    -> x23=3 (proves unsigned semantics)
        uut.imem.mem[34] = 32'h015B6463; // BLTU x22, x21, +8  -> unsigned 1<0xFFFFFFFF? true -> taken
        uut.imem.mem[35] = 32'h3E700C13; // ADDI x24, x0, 999  -> SKIPPED
        uut.imem.mem[36] = 32'h00000013; // NOP SKIPPED
        uut.imem.mem[37] = 32'h04000C13; // ADDI x24, x0, 64   -> x24=64  <BLTU taken target>
        uut.imem.mem[38] = 32'h00000013; // NOP

        uut.imem.mem[39] = 32'h016AF463; // BGEU x21, x22, +8  -> unsigned 0xFFFFFFFF>=1? true -> taken
        uut.imem.mem[40] = 32'h3E700C93; // ADDI x25, x0, 999  -> SKIPPED
        uut.imem.mem[41] = 32'h00000013; // NOP SKIPPED
        uut.imem.mem[42] = 32'h01100C93; // ADDI x25, x0, 17   -> x25=17  <BGEU taken target>
        uut.imem.mem[43] = 32'h015B7463; // BGEU x22, x21, +8  -> unsigned 1>=0xFFFFFFFF? false -> NOT taken
        uut.imem.mem[44] = 32'h01500D13; // ADDI x26, x0, 21   -> x26=21 (fallthrough proof)
        uut.imem.mem[45] = 32'h00000013; // NOP

        // Reset
        #25;
        rst_n = 1;

        // Ample margin: ~46 instructions plus one flush bubble per taken
        // branch/jump (9 taken) plus pipeline fill. 120 cycles is generous.
        wait_cycles(120);

        $display("--- AUIPC / JALR ---");
        check_reg(1, 32'h00005000, "AUIPC x1 = PC+0x5000");
        check_reg(3, 32'd12,       "JALR  x3 = return addr (12)");
        check_reg(9, 32'd0,        "JALR did not fall through (x9 untouched)");
        check_reg(5, 32'd55,       "JALR jumped to x5=55");

        $display("\n--- BGE (signed) ---");
        check_reg(15, 32'd1,  "BGE not-taken fallthrough (x15=1)");
        check_reg(16, 32'd42, "BGE taken target (x16=42)");

        $display("\n--- BNE ---");
        check_reg(19, 32'd7,  "BNE not-taken fallthrough (x19=7)");
        check_reg(20, 32'd88, "BNE taken target (x20=88)");

        $display("\n--- BLTU (unsigned) ---");
        check_reg(23, 32'd3,  "BLTU not-taken fallthrough (x23=3, proves unsigned compare)");
        check_reg(24, 32'd64, "BLTU taken target (x24=64)");

        $display("\n--- BGEU (unsigned) ---");
        check_reg(25, 32'd17, "BGEU taken target (x25=17)");
        check_reg(26, 32'd21, "BGEU not-taken fallthrough (x26=21)");

        $display("\n=== Summary: %0d passed, %0d failed ===", pass_count, fail_count);
        if (fail_count == 0)
            $display("ALL TESTS PASSED!");
        else
            $display("SOME TESTS FAILED!");

        $finish;
    end

endmodule
